### ISSUE TITLE
pub get failed (1) when trying to install maps_toolkit 

### ISSUE THREAD

**Issue by MRANASSPRO** [kb0/maps_toolkit#1]
> Because every version of flutter_test from sdk depends on pedantic 1.7.0 and every version of maps_toolkit depends on pedantic ^1.8.0, flutter_test from sdk is incompatible with maps_toolkit.
pub get failed (1)

**Comment by wowagenciacriativa** [comment]
same problem...

**Comment by kb0** [comment]
Move pedantic into dev_dependencies
