### ISSUE TITLE
geodesic?

### ISSUE THREAD

**Issue by subzero911** [kb0/maps_toolkit#11]
`PolygonUtil.containsLocation` - what does `geodesic` parameter mean? Should it be true or false?
I just want to check if my position is inside polygon or not

**Comment by kb0** [comment]
The polygon edge is composed of great circle segments if geodesic is true, and of Rhumb segments otherwise. For ex. - 
https://www.edumedia-sciences.com/en/media/924-rhumb-line-versus-great-circle
