### ISSUE TITLE
Change Earth Radius

### ISSUE THREAD

**Issue by RuyVictor** [kb0/maps_toolkit#31]
The SphericalUitl & PolygonUtil class contains the incorrect earth radius, change it from 6371009.0 to 6378137.0.
The results will be the same as lib javascript V3.

**Comment by kb0** [comment]
Earth radius 6371009 from Android Maps Utils - https://github.com/googlemaps/android-maps-utils/blob/main/library/src/main/java/com/google/maps/android/MathUtil.java

**Comment by RuyVictor** [comment]
@kb0 
Please do not ignore, the correct measurement is WGS84 ellipsoid, which is officially recognized. The Google Maps library for JavaScript is constantly changing compared to the Android library. By making this change, you will consequently provide better support for google_maps_flutter and flutter_map, as they follow WGS84.

https://developers.google.com/maps/documentation/javascript/reference/geometry?hl=en-us#spherical

https://gscommunitycodes.usf.edu/geoscicommunitycodes/public/geophysics/Gravity/earth_shape.php#:~:text=The%20radius%20of%20Earth%20at,a%20value%20of%201/230.

**Comment by RuyVictor** [comment]
Because of this situation, I had to fork their lib to adjust the correct length.

**Comment by RuyVictor** [comment]
Because of this situation, I had to locally fork your lib project to adjust the correct length.
