### ISSUE TITLE
Return driving distance on ComputeDistanceBetween

### ISSUE THREAD

**Issue by d-apps** [kb0/maps_toolkit#6]
Is it possible to add a route type parameter (for example as enum) to get driving distance between two points?

SphericalUtil.computeDistanceBetween(latLngFrom, latLngTo, **RouteType.DRIVING**)

**Comment by kb0** [comment]
This library only support mathematics functions to calculate distance, area or heading without any integrations with other services like Google Maps, Bing Maps or OpenStreetMaps.
