### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by SametSahin10** [kb0/maps_toolkit#9]
Hello, do you have any plans to support null safety?

**Comment by junaidlodhi22** [comment]
in my application, only this package is remaining with null safety

**Comment by SametSahin10** [comment]
@junaidlodhi22 How are you making use of this package? I might have a suggestion for you.

**Comment by junaidlodhi22** [comment]
I am using contains location method inside a polygon

**Comment by SametSahin10** [comment]
I've been using this package to calculate the distance between to lat-long pairs. I could suggest using [latlong2](https://pub.dev/packages/latlong2) to do that but your needs are apparently different than mine.

**Comment by allanwolski** [comment]
+1

**Comment by EverTorrez** [comment]
> en mi aplicación, solo este paquete permanece con seguridad nula

a la mia igual

**Comment by kb0** [comment]
added at v.2.0.0
